#!/bin/sh -e
# used for initramfs
mount -t sysfs none /sys
mount -t proc none /proc
mount -t tmpfs none /dev

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

init='/bin/busybox init'
for i in $(cat /proc/cmdline); do
	case $i in
		init=/init|init=init)
			# Avoid endless loop
			: ;;
		init=*)
			init=${i#init=} ;;
		noshell)
			sed -i '/^tty[23]/s/^/#/' /etc/inittab ;;
	esac
done
exec $init
