#!/bin/bash
#
SOS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EABI_DIR="$SOS_DIR/toolchain_prebuilt/arm-2011.03/bin"

OPTS=

ncpu=$(grep -c ^processor /proc/cpuinfo)
if [ "$ncpu" -gt 1 ]; then
    OPTS="$OPTS -j$ncpu"
fi

make -C uboot paz00_config CROSS_COMPILE="$EABI_DIR/arm-none-linux-gnueabi-" O=$PWD/build/uboot $OPTS || exit 1
make -C uboot CROSS_COMPILE="$EABI_DIR/arm-none-linux-gnueabi-" O=$PWD/build/uboot $OPTS || exit 1

ln -sf $PWD/build/uboot/u-boot-dtb-tegra.bin build/uboot.bin
