#!/bin/bash
#

rel=$(cat release)

rm -f build/target/init
install sosboot/init build/target

fakeroot ./scripts/pack_initrd -f build/initrd-large.img build/target || exit 1

./build/uboot/tools/mkimage -n "sos-$rel" -A arm -O linux -T ramdisk -C gzip -d ./build/initrd-large.img ./build/initrd-uboot || exit 1
create_bootimage/create_image.pl ./build/uboot.bin ./build/zImage ./build/initrd-uboot ./build/tegra20-paz00.dtb ./config/uboot.scr sos-uboot-$rel-$(date +%y-%m-%d).bin
ls -l  sos-uboot-$rel-$(date +%y-%m-%d).bin
echo "build/tegrarcm --bct=bct/ac100-micron.bct --bootloader=sos-uboot-${rel}-$(date +%y-%m-%d).bin --loadaddr=0x108000"
