#!/bin/bash
#
SOS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EABI_DIR="$SOS_DIR/toolchain_prebuilt/arm-linux-gnueabi-linaro_4.9.1-2014.07/bin"

if [[ :$PATH: == *:"$EABI_DIR":* ]] ; then
    echo "$EABI_DIR on bash path"
else
    echo "Add $EABI_DIR to bash path"
    export PATH=$PATH:$EABI_DIR
fi

OPTS=

ncpu=$(grep -c ^processor /proc/cpuinfo)
if [ "$ncpu" -gt 1 ]; then
    OPTS="$OPTS -j$ncpu"
fi

make -C kernel dtbs ARCH=arm CROSS_COMPILE="ccache arm-linux-gnueabi-" O=$PWD/build/kernel $OPTS zImage

ln -sf kernel/arch/arm/boot/zImage build/zImage
ln -sf kernel/arch/arm/boot/dts/tegra20-paz00.dtb build/tegra20-paz00.dtb
cat build/zImage build/tegra20-paz00.dtb > build/zImage-combined

