#!/bin/bash
#

OPTS=

ncpu=$(grep -c ^processor /proc/cpuinfo)
if [ "$ncpu" -gt 1 ]; then
    OPTS="$OPTS -j$ncpu"
fi

pushd tegrarcm
./autogen.sh || exit 1
popd
make -C tegrarcm $OPTS || exit 1

ln -sf $PWD/tegrarcm/src/tegrarcm build/tegrarcm
