#!/bin/bash
#

if [ -f build/initrd.img ]; then
    echo
    echo "Cleaning sosboot initrd image..."
    cd build
    rm initrd*
    cd ..
fi

if [ -f sosboot-ng-r1-alpha.img ]; then
    echo 
    echo "Cleaning sosboot image..."
    rm sosboot-ng-r1-alpha.img
fi

echo "done."

