#!/bin/bash
#

mkdir -p build/kernel
cp config/paz00_sosboot_defconfig kernel/arch/arm/configs/

make -C kernel ARCH=arm CROSS_COMPILE="ccache arm-none-linux-gnueabi-" O=$PWD/build/kernel paz00_sosboot_defconfig

