#!/bin/bash
#

SOS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EABI_DIR="$SOS_DIR/toolchain_prebuilt/arm-2014.05/"

if [[ :$PATH: == *:"$EABI_DIR":* ]] ; then
    echo "$EABI_DIR on bash path"
else
    echo "Add $EABI_DIR to bash path"
    export PATH=$PATH:$EABI_DIR
fi

mkdir -p build/buildroot
mkdir -p build/target

ln -sf ../target build/buildroot/target

sed -e 's,$EABI_DIR,'"$EABI_DIR"',' config/buildroot_paz00_defconfig > buildroot/configs/paz00_defconfig

cp config/busybox.config buildroot/package/busybox/busybox.config
#cp config/buildroot_paz00_defconfig buildroot/configs/paz00_defconfig
#cp config/buildroot.config build/buildroot/.config
#cp config/inittab buildroot/system/skeleton/etc/inittab

make -C buildroot O=$PWD/build/buildroot paz00_defconfig


