#!/bin/bash
#

if [ ! -d ac100-self-installers ]; then
    echo
    echo "Cloning ac100-self-installers from git..."
    git clone git://github.com/Stuw/ac100-self-installers.git
fi

cd ac100-self-installers

echo
echo "Fetching updates..."
git fetch --all --prune

echo
echo "Checking out..."
detach=""
git help checkout | grep -r '\-\-detach' > /dev/null
res=$?
if [[ "$res" == "0" ]]; then
	detach="--detach"
fi
git checkout -f
git clean -f -d

cd ..

#echo
#for p in patches/ac100-self-installers-*.patch; do
#    echo "Applying patch $p ..."
#    patch -d buildroot -p1 < $p
#    echo
#done

echo "done."

