#!/bin/bash

TOOLCHAIN=arm-2011.03-41-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2

if [ ! -d scripts/toolchain_prebuilt ]; then
mkdir scripts/toolchain_prebuilt
curl http://sourcery.mentor.com/public/gnu_toolchain/arm-none-linux-gnueabi/$TOOLCHAIN > scripts/toolchain_prebuilt/$TOOLCHAIN
tar xvfj scripts/toolchain_prebuilt/$TOOLCHAIN -C scripts/toolchain_prebuilt
fi

