#!/bin/bash
#

if [ ! -d uboot ]; then
    echo
    echo "Cloning uboot from git..."
    git clone git://gitorious.org/u-boot-ac100-exp/u-boot-ac100-exp.git uboot
fi

cd uboot

echo
echo "Fetching updates..."
git fetch --all --prune

echo
echo "Checking out..."
detach=""
git help checkout | grep -r '\-\-detach' > /dev/null
res=$?
if [[ "$res" == "0" ]]; then
	detach="--detach"
fi
git checkout -f $detach tegra-master-exp
git clean -f -d

cd ..

echo "done."

