#!/bin/bash
#

if [ ! -d uboot ]; then
    echo
    echo "Cloning uboot from git..."
    git clone git://gitorious.org/u-boot-ac100-exp/u-boot-ac100-exp.git uboot || exit 1
fi

cd uboot || exit 1

echo
echo "Fetching updates..."
git fetch --all --prune

echo
echo "Checking out..."
detach=""
git help checkout | grep -r '\-\-detach' > /dev/null
res=$?
if [[ "$res" == "0" ]]; then
	detach="--detach"
fi
git checkout -f $detach tegra-master-exp
git clean -f -d

cd ..

echo
for p in patches/uboot-*.patch; do
    echo "Applying patch $p ..."
    patch -d uboot -p1 < $p || exit 1
    echo
done

echo "done."

