#!/bin/bash

TOOLCHAIN=arm-2014.05-29-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2
TOOLCHAIN_KERNEL=arm-2011.03-41-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2

if [ ! -d scripts/toolchain_prebuilt ]; then
mkdir scripts/toolchain_prebuilt
curl http://sourcery.mentor.com/public/gnu_toolchain/arm-none-linux-gnueabi/$TOOLCHAIN > scripts/toolchain_prebuilt/$TOOLCHAIN
curl http://sourcery.mentor.com/public/gnu_toolchain/arm-none-linux-gnueabi/$TOOLCHAIN_KERNEL > scripts/toolchain_prebuilt/$TOOLCHAIN_KERNEL
tar xvfj scripts/toolchain_prebuilt/$TOOLCHAIN -C scripts/toolchain_prebuilt
tar xvfj scripts/toolchain_prebuilt/$TOOLCHAIN_KERNEL -C scripts/toolchain_prebuilt
fi

