#!/bin/bash
#

if [ ! -d kernel ]; then
    mkdir -p download
    echo "Downloading kernel..."
    # 2.6.38 ?
    #kernel_url=http://gitorious.org/ac100/marvin24s-kernel/archive-tarball/ca20bea1
    # 3.8
    kernel_url=http://gitorious.org/ac100/marvin24s-kernel/archive-tarball/linux-ac100-3.8
    wget "${kernel_url}" -O download/kernel.tar.gz
    if [[ "$(file download/kernel.tar.gz)" =~ "text" ]]; then
        cat download/kernel.tar.gz
        echo
        exit 1
    fi
    
    echo "Extracting kernel..."
    tar xzf download/kernel.tar.gz
    mv ac100-marvin24s-kernel kernel

    echo
    for p in patches/kernel-*.patch; do
        echo "Applying patch $p ..."
        patch -d kernel -p1 < $p
        echo
    done
fi

