#!/bin/bash
#

if [ ! -d create_bootimage ]; then
    echo "Downloading createimage.pl..."
    create_image_url=git://gitorious.org/uboot-ac100/create_bootimage.git
    git clone "${create_image_url}"
    ln -s $PWD/create_bootimage/create_image.pl $PWD/build
fi

ln -s $PWD/create_bootimage/create_image.pl $PWD/build
