#!/bin/bash
#

if [ ! -d kernel ]; then
    echo
    echo "Cloning kernel from git..."
    git clone git://gitorious.org/ac100/marvin24s-kernel.git
    mv marvin24s-kernel kernel
    cd kernel
    git checkout -f linux-ac100-3.8
fi

echo "done."

